#738: Extend ComputedBoundsAction with routing points
eclipse-glsp/glsp-server pull request #181
Opened 2022-10-15 16:34 UTC by martin-fleck-at

Part of https://github.com/eclipse-glsp/glsp/issues/738

2022-10-16 13:44 UTC, tortmayr requested changes
Thanks Martin. Code seems to work fine. 
I have tested it by changing the routerKind of the workflow example edge creation handlers to "manhattan".

I have a few inline suggestions and one more general question:

I personally find it a bit odd that an action called "ComputedBoundsAction" also contains the routing points. Also by directly adapting the "ComputedBoundsAction" which we might introduce an inconsistency/incompatibility with the original ComputedBoundsAction from sprotty.

Maybe it would be better to use a dedicated `ComputedRoutingPointsOperation` and wrap it together with the `ComputedBoundsOperation` in an "CompoundOperation`?

2022-10-17 10:32 UTC, martin-fleck-at commented on plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/LayoutUtil.java
> +   public static void applyRoutingPonts(final ElementAndRoutingPoints routingPoints, final GModelIndex index) {
Ah, good catch, thank you!

2022-10-17 10:33 UTC, martin-fleck-at commented on plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/gmodel/GModelChangeRoutingPointsHandler.java
>  package org.eclipse.glsp.server.gmodel;
Done!

2022-10-17 10:45 UTC, martin-fleck-at commented
@tortmayr Thank you very much for your feedback, I adapted the code accordingly. Regarding a dedicated operation for the routing points, I opted against it since the client-side layout information is currently all part of the `ComputedBoundsAction`, also the alignment. Furthermore, this action carries a specific meaning as the `ComputedBoundsActionHandler` will directly submit the model afterwards, so splitting that into two operations would make their handling more difficult.

2022-11-14 16:20 UTC, merged