#122 #123 Centralize configuration in the server
eclipse-glsp/glsp-server pull request #90
Opened 2020-11-24 12:28 UTC by CamilleLetavernier

- Merge ServerLayoutConfiguration into DiagramConfiguration
- Centralize model update protocol in Model Submission Handler

This addresses both eclipse-glsp/glsp/issues/122 and eclipse-glsp/glsp/issues/123, as the changes to needsClientLayout affects the way the ModelSubmissionHandler is implemented.

2020-11-24 12:29 UTC, CamilleLetavernier commented
Note: I also have the corresponding client-side changes (Which simply removes the needsClientLayout parameter from the client); I'll create a separate PR if these changes are fine. The client-side changes aren't actually required (strictly speaking), as the extra parameter would simply be ignored by the server.

2020-12-09 09:36 UTC, tortmayr requested changes
Looks good to me. I only have to minor change requests :wink:

2020-12-09 09:36 UTC, tortmayr commented on plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/ModelSubmissionHandler.java
>     public List<Action> doSubmitModel(final boolean update, final GModelState modelState) {
Maybe just call it `submitModel`?

2020-12-14 16:20 UTC, planger commented
This looks very useful to me! Can we get this merged soon?
I'd like to address https://github.com/eclipse-glsp/glsp/issues/119 based on this change too, because the model submission handler could just invoke an extended version of the model factory to translate model state (with the custom model source) into the new version of the gmodel before submitting it to the client.
This would then also centralize the translation from original model source to gmodel.

2020-12-16 10:19 UTC, planger commented
Closed in favor of https://github.com/eclipse-glsp/glsp-server/pull/95

2020-12-16 10:19 UTC, closed without merging